### ISSUE TITLE
Add message content parameter in "preset templates" 

### ISSUE THREAD

**Issue by mortenbra** [vincentmorneau/oracle-rwd-email-template-api#2]
I suggest to add a (record type) message content parameter to the preset templates, so they can be used without having to edit and recompile the package just to change the message content.

Some pseudo-code:

-- add to package spec

type t_message_content is record (
        logo_url          varchar2(4000),
        title             varchar2(4000),
        welcome_title     varchar2(4000),
        sub_welcome_title varchar2(4000),
        top_paragraph     varchar2(4000),
        bottom_paragraph  varchar2(4000),
        social_title      varchar2(4000),
        contact_info      varchar2(4000),
        contact_phone     varchar2(4000),
        contact_email     varchar2(4000),
        footer_links      varchar2(4000)
);

-- modify package body

   /\* Basic Template */
  -- this now has a parameter
    FUNCTION basic (p_content in t_message_content) return clob IS
        l_body              clob;

```
BEGIN
    /* 
    Initialize Variables
  -- this section can now be removed
    */  

    /* Build the email body */

  -- this now uses the parameter values instead of the local variables

    l_body :=   print_global_body(
                    print_default_body_header(p_content.logo_url, p_content.title)
                    || print_container(
                        print_row(
                            print_column_wrapper(
                                print_col_12(
                                    print_standard_td(
                                        print_h1(p_content.welcome_title)
                                        || print_paragraph_lead(p_content.sub_welcome_title)
                                        || print_paragraph(p_content.top_paragraph)
                                        || print_paragraph(p_content.top_paragraph)
                                        || print_paragraph(p_content.top_paragraph)
                                    ) 
                                )
                            )
```

-- and so on...

**Comment by vincentmorneau** [comment]
Very good point. I'll revisit this week. Thanks for your input!
