### ISSUE TITLE
l_content.logo_url cant read APP_IMAGES 

### ISSUE THREAD

**Issue by jDimitrako** [vincentmorneau/oracle-rwd-email-template-api#4]
Hi Vincent,
i try to insert  <img src="#APP_IMAGES#logo.png/> to l_content.logo_url but without success.Any thought or tip?

**Comment by vincentmorneau** [comment]
I don't think you can use #APP_IMAGES# in packages. Try `apex_application.g_flow_images`

**Comment by jDimitrako** [comment]
and something more.What about licence at this project? is any contribution permitted?

**Comment by vincentmorneau** [comment]
Contributions are welcome. What kind of pull requests are you thinking of?

**Comment by jDimitrako** [comment]
first of all I think that parameterization needs more work. like buttons labels, button url etc. then to create some new templates.. what do you think?

**Comment by vincentmorneau** [comment]
Yes. I agree. This project was adapted from Foundation for Email 1.0. Now they've upgraded to 2.x a while ago and I intended to upgrade a well with much better parameterization.

See the new Foundation for Emails here: https://github.com/zurb/foundation-emails/releases 

Time is only keeping me up right now.

How much are you wanting to contribute?

**Comment by jDimitrako** [comment]
Yes, i understand. My time is not limitless too, but  i want to contribute as much is possible. Give me a general plan about the upgrade plan that you have in your mind. To have a clear view about project and see how i can help at that. Or you have something else in your mind? 

Update: I close the issue, when you have time, contact with me.
